routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','frontend\DesignController@index')->name('index');
Route::get('/services','frontend\DesignController@services')->name('services');
Route::get('/car', 'frontend\DesignController@cars')->name('cars');
Route::get('/about', 'frontend\DesignController@about')->name('about');
/*Route::get('/blog', function () {return view('frontend.pages.blog');})->name('blog');*/
Route::get('/single', function () {return view('frontend.pages.single');})->name('single');
Route::get('/contact/{id?}', 'frontend\DesignController@contact')->name('contact');
Route::post('/contact/store', 'frontend\DesignController@contactStore')->name('client.store');
Route::post('/get/cars', 'frontend\DesignController@getCars')->name('get.cars');
Route::get('admin', 'Auth\LoginController@showLoginForm');
Route::post('admin', 'Auth\LoginController@login');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'AuthenticateUser','namespace'=>'backend','prefix' => 'admin', 'as' => 'admin.'], function () {

    Route::get('/dashboard','HomeController@index')->name('dashboard');
    Route::get('/cars/manage','CarsController@index')->name('cars.manage');
    Route::get('/cars/add','CarsController@create')->name('cars.add');
    Route::post('/cars/store','CarsController@store')->name('cars.store');
    Route::post('/cars/delete/{id}','CarsController@destroy')->name('cars.delete');
    Route::get('/cars/edit/{id}','CarsController@edit')->name('cars.edit');
    Route::get('/cars/get/','ClientController@index')->name('get.clients');
    Route::get('/cars/show/{id}','ClientController@show')->name('get.show');

    Route::get('/cms/about','CmsController@index')->name('cms.about');
    Route::get('/cms/about/add','CmsController@create')->name('cms.add');
    Route::post('/cms/about/store','CmsController@store')->name('cms.store');
    Route::get('/cms/about/edit/{id}','CmsController@edit')->name('cms.edit');
    Route::post('/cms/about/delete/{id}','CmsController@destroy')->name('cms.delete');

    Route::get('/cms/service','CmsController@serviceindex')->name('cms.service');
    Route::get('/cms/service/add','CmsController@servicecreate')->name('cms.service.add');
    Route::post('/cms/service/store','CmsController@servicestore')->name('cms.service.store');
    Route::get('/cms/service/edit/{id}','CmsController@serviceedit')->name('cms.service.edit');
    Route::post('/cms/service/delete/{id}','CmsController@servicedestroy')->name('cms.service.delete');

    Route::get('/cms/contact','CmsController@contactindex')->name('cms.contact');
    Route::get('/cms/contact/add','CmsController@contactcreate')->name('cms.contact.add');
    Route::post('/cms/contact/store','CmsController@contactstore')->name('cms.contact.store');
    Route::get('/cms/contact/edit/{id}','CmsController@contactedit')->name('cms.contact.edit');
    Route::post('/cms/contact/delete/{id}','CmsController@contactdestroy')->name('cms.contact.delete');

    Route::get('/seo','SeoController@index')->name('seo');
    Route::get('/seo/add','SeoController@create')->name('seo.add');
    Route::post('/seo/store','SeoController@store')->name('seo.store');
    Route::get('/seo/edit/{id}','SeoController@edit')->name('seo.edit');
    Route::post('/seo/delete/{id}','SeoController@destroy')->name('seo.delete');

});

resources/views/backend/modules/layout/app.blade.php
<!DOCTYPE html>
<html>
@include('backend.modules.layout.headercdn')
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
    <header class="main-header">
        <a href="{{route('admin.dashboard')}}" class="logo">
            <span class="logo-mini"><b>S-T</b></span>
            <span class="logo-lg"><b>SaiTravels</b></span>
        </a>
        <nav class="navbar navbar-static-top">
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    {{--@include('backend.layouts.message')--}}
                    {{--@include('backend.layouts.notification')--}}
                    @include('backend.modules.layout.task')
                    @include('backend.modules.layout.userdropbox')
                    {{--<li>
                        <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                    </li>--}}
                </ul>
            </div>
        </nav>
    </header>
    @include('backend.modules.layout.navigation')

resources/views/backend/modules/layout/foot.blade.php
<div class="control-sidebar-bg"></div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="{{ URL::asset('backend/adminlte/bower_components/jquery-ui/jquery-ui.min.js') }}"></script>
<script>
    $.widget.bridge('uibutton', $.ui.button);
</script>
<script src="{{ URL::asset('backend/adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<script src="{{ URL::asset('backend/adminlte/bower_components/raphael/raphael.min.js') }}"></script>
<script src="{{ URL::asset('backend/adminlte/bower_components/morris.js/morris.min.js') }}"></script>
<script src="{{ URL::asset('backend/adminlte/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js') }}"></script>
<script src="{{ URL::asset('backend/adminlte/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js') }}"></script>
<script src="{{ URL::asset('backend/adminlte/plugins/jvectormap/jquery-jvectormap-world-mill-en.js') }}"></script>
<script src="{{ URL::asset('backend/adminlte/bower_components/jquery-knob/dist/jquery.knob.min.js') }}"></script>
<script src="{{ URL::asset('backend/adminlte/bower_components/moment/min/moment.min.js') }}"></script>
<script src="{{ URL::asset('backend/adminlte/bower_components/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
<script src="{{ URL::asset('backend/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') }}"></script>
<script src="{{ URL::asset('backend/adminlte/dist/js/adminlte.min.js') }}"></script>
<script src="{{ URL::asset('backend/adminlte/dist/js/demo.js') }}"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/additional-methods.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="https://cdn.ckeditor.com/4.5.1/standard/ckeditor.js"></script>
<script>
    $(window).on('load', function() {
        $('.content-wrapper').attr('style','min-height:1359px;');
        $('.ion').attr('style','margin-top:13px;');
    });




    $(document).ready(function () {
        // Replace the <textarea id="editor1"> with a CKEditor
        // instance, using default configuration.
        CKEDITOR.editorConfig = function(config) {
            config.language = 'es';
            config.uiColor = '#F7B42C';
            config.height = 300;
            config.toolbarCanCollapse = true;

        };
        CKEDITOR.replace('description');

    });
</script>


</body>
</html>

resources/views/backend/modules/layout/head.blade.php
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="{{ URL::asset('vendor/adminlte/vendor/bootstrap/dist/css/bootstrap.css')}}">
    <link rel="stylesheet" href="{{ URL::asset('vendor/adminlte/vendor/font-awesome/css/fontawesome.css')}}">
    <link rel="stylesheet" href="{{ URL::asset('vendor/adminlte/vendor/Ionicons/css/ionicons.css')}}">
    <link rel="stylesheet" href="{{ URL::asset('vendor/adminlte/dist/css/AdminLTE.min.css')}}">
    <link rel="stylesheet" href="{{ URL::asset('vendor/adminlte/plugins/iCheck/square/blue.css') }}">
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    <style>
        .error{
            color: red;
        }
       
    </style>
</head>

resources/views/backend/modules/layout/headercdn.blade.php
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="{{ URL::asset('backend/adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ URL::asset('backend/adminlte/bower_components/font-awesome/css/font-awesome.min.css') }}">
    <link rel="stylesheet" href="{{ URL::asset('backend/adminlte/bower_components/Ionicons/css/ionicons.min.css') }}">
    <link rel="stylesheet" href="{{ URL::asset('backend/adminlte/dist/css/AdminLTE.min.css') }}">
    <link rel="stylesheet" href="{{ URL::asset('backend/adminlte/dist/css/skins/_all-skins.min.css') }}">
    <link rel="stylesheet" href="{{ URL::asset('backend/adminlte/bower_components/morris.js/morris.css') }}">
    <link rel="stylesheet" href="{{ URL::asset('backend/adminlte/bower_components/jvectormap/jquery-jvectormap.css') }}">
    <link rel="stylesheet" href="{{ URL::asset('backend/adminlte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') }}">
    <link rel="stylesheet" href="{{ URL::asset('backend/adminlte/bower_components/bootstrap-daterangepicker/daterangepicker.css') }}">
    <link rel="stylesheet" href="{{ URL::asset('backend/adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css') }}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.16/datatables.min.css"/>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap.min.css"/>
    @toastr_css
    <style>
        .small-box{
            border-radius: 15px;
        }
        .unique{
            margin-top: 15px;
        }
    </style>
</head>

resources/views/backend/modules/layout/message.blade.php
<li class="dropdown messages-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="fa fa-envelope-o"></i>
        <span class="label label-success">4</span>
    </a>
    <ul class="dropdown-menu">
        <li class="header">You have 4 messages</li>
        <li>
            <!-- inner menu: contains the actual data -->
            <ul class="menu">
                <li><!-- start message -->
                    <a href="#">
                        <div class="pull-left">
                            <img src="{{URL::asset('dash/img/user4-128x128.jpg')}}" class="img-circle" alt="User Image">
                        </div>
                        <h4>
                            Support Team
                            <small><i class="fa fa-clock-o"></i> 5 mins</small>
                        </h4>
                        <p>Why not buy a new awesome theme?</p>
                    </a>
                </li>
                <!-- end message -->
                <li>
                    <a href="#">
                        <div class="pull-left">
                            <img src="{{URL::asset('dash/img/user4-128x128.jpg')}}" class="img-circle" alt="User Image">
                        </div>
                        <h4>
                            AdminLTE Design Team
                            <small><i class="fa fa-clock-o"></i> 2 hours</small>
                        </h4>
                        <p>Why not buy a new awesome theme?</p>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <div class="pull-left">
                            <img src="{{URL::asset('dash/img/user4-128x128.jpg')}}" class="img-circle" alt="User Image">
                        </div>
                        <h4>
                            Developers
                            <small><i class="fa fa-clock-o"></i> Today</small>
                        </h4>
                        <p>Why not buy a new awesome theme?</p>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <div class="pull-left">
                            <img src="{{URL::asset('dash/img/user4-128x128.jpg')}}" class="img-circle" alt="User Image">
                        </div>
                        <h4>
                            Sales Department
                            <small><i class="fa fa-clock-o"></i> Yesterday</small>
                        </h4>
                        <p>Why not buy a new awesome theme?</p>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <div class="pull-left">
                            <img src="{{URL::asset('dash/img/user4-128x128.jpg')}}" class="img-circle" alt="User Image">
                        </div>
                        <h4>
                            Reviewers
                            <small><i class="fa fa-clock-o"></i> 2 days</small>
                        </h4>
                        <p>Why not buy a new awesome theme?</p>
                    </a>
                </li>
            </ul>
        </li>
        <li class="footer"><a href="#">See All Messages</a></li>
    </ul>
</li>

resources/views/backend/modules/layout/navigation.blade.php
<aside class="main-sidebar">
    <section class="sidebar">
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{{ URL::asset('backend/adminlte/dist/img/user2-160x160.jpg') }}" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>{{ Auth::user()->name}} </p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <form class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat" disabled>
                    <i class="fa fa-search"></i>
                </button>
              </span>
            </div>
        </form>
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">MAIN NAVIGATION</li>

           
            <li>
                <a href="{{route('admin.dashboard')}}">
                    <i class="fa fa-dashboard"></i>
                    <span>Dashboard</span>
                    <span class="pull-right-container"></span>
                </a>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-dashboard"></i> <span>Cars</span>
                    <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{route('admin.cars.manage')}}"><i class="fa fa-circle-o text-yellow"></i>Manage Cars</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-dashboard"></i> <span>Clients</span>
                    <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{route('admin.get.clients')}}"><i class="fa fa-circle-o text-yellow"></i>List Clients Inquiry</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-dashboard"></i> <span>CMS</span>
                    <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{route('admin.cms.about')}}"><i class="fa fa-circle-o text-yellow"></i>About</a></li>
  <li><a href="{{route('admin.cms.service')}}"><i class="fa fa-circle-o text-yellow"></i>Service</a></li>
                    <li><a href="{{route('admin.cms.contact')}}"><i class="fa fa-circle-o text-yellow"></i>Contact</a></li>
                </ul>
            </li>
            <li>
                <a href="{{route('admin.seo')}}">
                    <i class="fa fa-dashboard"></i>
                    <span>Seo Module</span>
                    <span class="pull-right-container"></span>
                </a>
            </li>
            {{--<li class="treeview">
                <a href="#">
                    <i class="fa fa-dashboard"></i> <span>Campaign Management</span>
                    <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{route('admin.get.campaign')}}"><i class="fa fa-circle-o text-yellow"></i>List Campaign</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-dashboard"></i> <span>Content Management</span>
                    <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{route('admin.get.country')}}"><i class="fa fa-circle-o text-yellow"></i>Country</a></li>
                    --}}{{--<li><a href="{{route('admin.email.index')}}"><i class="fa fa-circle-o text-yellow"></i>E-Mail's</a></li>--}}{{--
                    <li><a href="{{route('admin.mail.get')}}"><i class="fa fa-circle-o text-yellow"></i>Mail Template</a></li>
                    <li><a href="{{route('admin.faq.get')}}"><i class="fa fa-circle-o text-yellow"></i>FAQ's</a></li>
                </ul>
            </li>--}}
        </ul>
    </section>
</aside>

resources/views/backend/modules/layout/notification.blade.php
<li class="dropdown notifications-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="fa fa-bell-o"></i>
        <span class="label label-warning">10</span>
    </a>
    <ul class="dropdown-menu">
        <li class="header">You have 10 notifications</li>
        <li>
            <!-- inner menu: contains the actual data -->
            <ul class="menu">
                <li>
                    <a href="#">
                        <i class="fa fa-users text-aqua"></i> 5 new members joined today
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-warning text-yellow"></i> Very long description here that may not fit into the
                        page and may cause design problems
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-users text-red"></i> 5 new members joined
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-shopping-cart text-green"></i> 25 sales made
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-user text-red"></i> You changed your username
                    </a>
                </li>
            </ul>
        </li>
        <li class="footer"><a href="#">View all</a></li>
    </ul>
</li>

resources/views/backend/modules/layout/task.blade.php
<?php
/*if(!isset(Auth::guard('admin')->user()->email) || Auth::guard('admin')->user()->email == '')
{
    header("Location: https:share.theflypost.com/admin");
    exit();
}
*/?>

resources/views/backend/modules/layout/userdropbox.blade.php
<li class="dropdown user user-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <img src="{{ URL::asset('backend/adminlte/dist/img/user2-160x160.jpg') }}" class="user-image" alt="User Image">
        <span class="hidden-xs">{{ Auth::user()->email}}</span>
    </a>
    <ul class="dropdown-menu">
        <li class="user-header">
            <img src="{{ URL::asset('backend/adminlte/dist/img/user2-160x160.jpg') }}" class="img-circle" alt="User Image">
            <p>
                {{ Auth::user()->name}} - Admin
                <small>Member since Nov. 2019</small>
            </p>
        </li>
        {{--<li class="user-body">
            <div class="row">
                <div class="col-xs-4 text-center">
                    <a href="#">Followers</a>
                </div>
                <div class="col-xs-4 text-center">
                    <a href="#">Sales</a>
                </div>
                <div class="col-xs-4 text-center">
                    <a href="#">Friends</a>
                </div>
            </div>
        </li>--}}
        <li class="user-footer">
            <div class="pull-left">
                <a href="#" class="btn btn-default btn-flat">
                    <span class="glyphicon glyphicon-user"></span> Profile
                </a>
            </div>
            <div class="pull-right">
                <a class="btn btn-default btn-flat" href="{{ route('logout') }}"
                   onclick="event.preventDefault();
                                        document.getElementById('logout-form').submit();">
                    <span class="glyphicon glyphicon-log-out"></span>
                    Sign out
                </a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </div>
        </li>
    </ul>
</li>

resources/views/backend/modules/layout/validation.blade.php
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/additional-methods.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

<script>
    $(document).ready(function () {
        $("#adminLogin").validate({
            rules:{
                email:{
                    required:true,
                    email:true,
                },
                password:{
                    required:true,
                }
            },
            messages:{
                email:{
                    required:"Please Enter Email To Login",
                    email:"Please Enter Valid Email To Login"
                },
                password:{
                    required:"Please Enter Password To Login"
                }
            }
        });
    });
</script>
<script>
    $(document).ready(function () {
        $("#adminReset").validate({
            rules:{
                email:{
                    required:true,
                    email:true,
                }
            },
            messages:{
                email:{
                    required:"Please Enter Email To Reset Password",
                    email:"Please Enter Valid Email To Login"
                }
            }
        });
    });
</script>
<script>
    $(document).ready(function () {
        $('#registerForm').validate({ // initialize the plugin
            rules: {
                user_name: {
                    required: true,
                },
                email:{
                    required:true,
                    email:true
                },
                firstname:{
                    required:true
                },
                lastname:{
                    required:true
                },
                skype:{
                    required:true
                },
                phone:{
                    required:true,
                    number:true,
                    minlength:10,
                    maxlength:10,
                },
                mobile:{
                    required:true,
                    number:true,
                    minlength:10,
                    maxlength:10
                },
                pass:{
                    required:true,
                    minlength:6
                },
                retype_pass:{
                    equalTo:"#pass",
                    required:true,
                    minlength:6
                },
                profile:{
                    required:true,
                    extension: "jpeg|jpg|png",
                    maxsize:200000
                },
                terms:{
                    required:true,
                },
                designation:{
                    required:true,
                    integer:true
                }
            },
            messages:{
                user_name: {
                    required: "Please Enter UserName",
                },
                email:{
                    required:"Please Enter Email-Address Properly",
                    email:"Please Enter Valid Email-Address"
                },
                firstname:{
                    required:"Please Enter FirstName"
                },
                lastname:{
                    required:"Please Enter LastName"
                },
                skype:{
                    required:"Please Enter SkypeId"
                },
                phone:{
                    required:"Please Enter Phone-Number",
                    number:"Please Enter Valid Phone-Number",
                    minlength:"Please Enter 10 digit Valid Phone-Number",
                    maxlength: "Please Enter 10 digit Valid Phone-Number",
                },
                mobile:{
                    required:"Please Enter Mobile-Number",
                    number:"Please Enter Valid Mobile-Number",
                    minlength:"Please Enter 10 digit Valid Mobile-Number",
                    maxlength:"Please Enter 10 digit Valid Mobile-Number",
                },
                pass:{
                    required:"Please Enter Password",
                    minlength:"InValid Password Length(6-Required)"
                },
                retype_pass:{
                    equalTo:"Confirm Password Not Matched",
                    required:"Please Enter Confirm Password",
                    minlength:"InValid Password Length(6-Required)"
                },
                profile:{
                    required:"Please Select Profile Image",
                    extension:"Invalid File (PNG|JPEG|JPG - Required)",
                    maxsize:"Please Select 2MB Image"
                },
                terms:{
                    required:"Terms And Condition Required"
                },
                designation:{
                    required:"Please Select Designation",
                    integer:"Please Select Proper Designation"
                }
            }
        });
    });
</script>