routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','frontend\DesignController@index')->name('index');
Route::get('/services','frontend\DesignController@services')->name('services');
Route::get('/car', 'frontend\DesignController@cars')->name('cars');
Route::get('/about', 'frontend\DesignController@about')->name('about');
/*Route::get('/blog', function () {return view('frontend.pages.blog');})->name('blog');*/
Route::get('/single', function () {return view('frontend.pages.single');})->name('single');
Route::get('/contact/{id?}', 'frontend\DesignController@contact')->name('contact');
Route::post('/contact/store', 'frontend\DesignController@contactStore')->name('client.store');
Route::post('/get/cars', 'frontend\DesignController@getCars')->name('get.cars');
Route::get('admin', 'Auth\LoginController@showLoginForm');
Route::post('admin', 'Auth\LoginController@login');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'AuthenticateUser','namespace'=>'backend','prefix' => 'admin', 'as' => 'admin.'], function () {

    Route::get('/dashboard','HomeController@index')->name('dashboard');
    Route::get('/cars/manage','CarsController@index')->name('cars.manage');
    Route::get('/cars/add','CarsController@create')->name('cars.add');
    Route::post('/cars/store','CarsController@store')->name('cars.store');
    Route::post('/cars/delete/{id}','CarsController@destroy')->name('cars.delete');
    Route::get('/cars/edit/{id}','CarsController@edit')->name('cars.edit');
    Route::get('/cars/get/','ClientController@index')->name('get.clients');
    Route::get('/cars/show/{id}','ClientController@show')->name('get.show');

    Route::get('/cms/about','CmsController@index')->name('cms.about');
    Route::get('/cms/about/add','CmsController@create')->name('cms.add');
    Route::post('/cms/about/store','CmsController@store')->name('cms.store');
    Route::get('/cms/about/edit/{id}','CmsController@edit')->name('cms.edit');
    Route::post('/cms/about/delete/{id}','CmsController@destroy')->name('cms.delete');

    Route::get('/cms/service','CmsController@serviceindex')->name('cms.service');
    Route::get('/cms/service/add','CmsController@servicecreate')->name('cms.service.add');
    Route::post('/cms/service/store','CmsController@servicestore')->name('cms.service.store');
    Route::get('/cms/service/edit/{id}','CmsController@serviceedit')->name('cms.service.edit');
    Route::post('/cms/service/delete/{id}','CmsController@servicedestroy')->name('cms.service.delete');

    Route::get('/cms/contact','CmsController@contactindex')->name('cms.contact');
    Route::get('/cms/contact/add','CmsController@contactcreate')->name('cms.contact.add');
    Route::post('/cms/contact/store','CmsController@contactstore')->name('cms.contact.store');
    Route::get('/cms/contact/edit/{id}','CmsController@contactedit')->name('cms.contact.edit');
    Route::post('/cms/contact/delete/{id}','CmsController@contactdestroy')->name('cms.contact.delete');

    Route::get('/seo','SeoController@index')->name('seo');
    Route::get('/seo/add','SeoController@create')->name('seo.add');
    Route::post('/seo/store','SeoController@store')->name('seo.store');
    Route::get('/seo/edit/{id}','SeoController@edit')->name('seo.edit');
    Route::post('/seo/delete/{id}','SeoController@destroy')->name('seo.delete');

});

app/Models/backend/Cms.php
<?php

namespace App\Models\backend;

use Illuminate\Database\Eloquent\Model;

class Cms extends Model
{
    protected $table = "cms_page";
    protected $fillable = ['page_name','description','status'];
    protected $primaryKey="id";
}

app/Http/Controllers/backend/CmsController.php
<?php

namespace App\Http\Controllers\backend;

use App\Models\backend\Cars;
use App\Models\backend\Cms;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\File;

class CmsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cmsAbout =Cms::where('page_name','about')->get();

        return view('backend.modules.cms.about.index')->with(compact('cmsAbout'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.modules.cms.about.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if(isset($request->editid)){
            $request->validate([
                'page_name' => 'required',
                'description'=> 'required',
            ]);
            $obj =  Cms::findorfail($request->editid);
        }else{
            $request->validate([
                'page_name' => 'required',
                'description'=> 'required',
            ]);
            $obj = new Cms();
        }

        $obj->page_name = $request['page_name'];
        $obj->description = $request['description'];

        $obj->save();

        if(isset($request->editid))
            toastr()->info('Data has been Updated successfully!');
        else
            toastr()->success('Data has been saved successfully!');

        return redirect()->route('admin.cms.about');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $cars = Cms::where('id',$id)->get();

        return view('backend.modules.cms.about.edit')->with(compact('cars'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Cms::where('id',$id)->delete();
        return response()->json(1);
    }


    public function serviceindex()
    {
        $cmsAbout =Cms::where('page_name','service')->get();

        return view('backend.modules.cms.service.index')->with(compact('cmsAbout'));
    }

    public function servicecreate()
    {
        return view('backend.modules.cms.service.add');
    }


    public function servicestore(Request $request)
    {
        if(isset($request->editid)){
            $request->validate([
                'page_name' => 'required',
                'description'=> 'required',
            ]);
            $obj =  Cms::findorfail($request->editid);
        }else{
            $request->validate([
                'page_name' => 'required',
                'description'=> 'required',
            ]);
            $obj = new Cms();
        }

        $obj->page_name = $request['page_name'];
        $obj->description = $request['description'];

        $obj->save();

        if(isset($request->editid))
            toastr()->info('Data has been Updated successfully!');
        else
            toastr()->success('Data has been saved successfully!');

        return redirect()->route('admin.cms.service');
    }

    public function serviceedit($id)
    {
        $cars = Cms::where('id',$id)->get();

        return view('backend.modules.cms.service.edit')->with(compact('cars'));
    }



    public function servicedestroy($id)
    {
        Cms::where('id',$id)->delete();
        return response()->json(1);
    }

    public function contactindex()
    {
        $cmsAbout =Cms::where('page_name','contact')->get();

        return view('backend.modules.cms.contact.index')->with(compact('cmsAbout'));
    }

    public function contactcreate()
    {
        return view('backend.modules.cms.contact.add');
    }


    public function contactstore(Request $request)
    {
        if(isset($request->editid)){
            $request->validate([
                'page_name' => 'required',
                'description'=> 'required',
            ]);
            $obj =  Cms::findorfail($request->editid);
        }else{
            $request->validate([
                'page_name' => 'required',
                'description'=> 'required',
            ]);
            $obj = new Cms();
        }

        $obj->page_name = $request['page_name'];
        $obj->description = $request['description'];

        $obj->save();

        if(isset($request->editid))
            toastr()->info('Data has been Updated successfully!');
        else
            toastr()->success('Data has been saved successfully!');

        return redirect()->route('admin.cms.contact');
    }

    public function contactedit($id)
    {
        $cars = Cms::where('id',$id)->get();

        return view('backend.modules.cms.contact.edit')->with(compact('cars'));
    }

    public function contactstroy($id)
    {
        Cms::where('id',$id)->delete();
        return response()->json(1);
    }
}

resources/views/backend/modules/cms/service/add.blade.php
@include('backend.modules.layout.app')
<div class="content-wrapper">
    <section class="content-header">
        <h1>
            &nbsp;&nbsp;&nbsp;Service Content Form
            <small>Preview</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li>Service</li>
            <li class="active"><a href="{{route('admin.cms.service')}}">Add Service</a></li>
        </ol>
    </section>
    <section class="content">
        <div class="col-md-10">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">Enter Details Of The Service</h3>
                </div>
                <!--================================ /.box-header =================================================-->
                <!--================================ form start ==================================================-->
                <form id="carForm" enctype="multipart/form-data" action="{{route('admin.cms.service.store')}}" method="post">
                    @csrf
                    <div class="box-body">
                        <div class="form-group">
                            <div class="col-md-6 unique">
                                <label>Page Name:</label>
                                <input type="text" id="page_name" class="form-control" name="page_name"
                                       placeholder="Page Name*:"
                                       value="{{old('page_name')}}">
                                @if($errors->has('page_name'))
                                    <span id="invalid-feedback" role="alert">
                                        <strong id="error" style="color: red">{{ $errors->first('page_name') }}</strong>
                                    </span>
                                @endif
                            </div>


                            <div class="col-md-12 unique" style="margin-bottom: 20px;">

                                    <label>Description:</label>
                                    <textarea name="description" id="description" rows="10" cols="80"></textarea>
                                @if($errors->has('description'))
                                    <span id="invalid-feedback" role="alert">
                                        <strong id="error" style="color: red">{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif
                            </div>

                    </div>
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </section>
</div>
@include('backend.modules.layout.foot')
@include('backend.modules.cars.script')

resources/views/backend/modules/cms/service/edit.blade.php
@include('backend.modules.layout.app')
<div class="content-wrapper">
    <section class="content-header">
        <h1>
            &nbsp;&nbsp;&nbsp;Service Form Update 
            <small>Preview</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li>Service</li>
            <li class="active"><a onclick="location.reload()" style="cursor: pointer">Add Service</a></li>
        </ol>
    </section>
    <section class="content">
        <div class="col-md-10">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">Enter Details Of The Service</h3>
                </div>
                <!--================================ /.box-header =================================================-->
                <!--================================ form start ==================================================-->
                <form id="carForm" enctype="multipart/form-data" action="{{route('admin.cms.service.store')}}" method="post">
                    @csrf
                    <div class="box-body">
                        <div class="form-group">
                            <div class="col-md-6 unique">
                                <label>Page Name:</label>
                                <input type="hidden" name="editid" value="{{$cars[0]->id}}"></input>
                                <input type="text" id="page_name" class="form-control" name="page_name"
                                       placeholder="Page Name*:"
                                       value="{{old('page_name') ? old('page_name') : ( ($cars[0]->page_name) ? $cars[0]->page_name : '' )}}">
                                @if($errors->has('page_name'))
                                    <span id="invalid-feedback" role="alert">
                                        <strong id="error" style="color: red">{{ $errors->first('page_name') }}</strong>
                                    </span>
                                @endif
                            </div>

                            <div class="col-md-12 unique" style="margin-bottom: 20px;">

                                <label>Description:</label>
                                <textarea name="description" id="description" rows="10" cols="80"
                                          value="{{old('description') ? old('description') : ( ($cars[0]->description) ? $cars[0]->description : '' )}}"></textarea>
                                              @if($errors->has('description'))
                                              <span id="invalid-feedback" role="alert">
                                <strong id="error" style="color: red">{{ $errors->first('description') }}</strong>
                                </span>
                                @endif

                            </div>


                        </div>


                    </div>
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary btn-lg btn-block">Update</button>
                    </div>
                </form>
            </div>
        </div>
    </section>
</div>
@include('backend.modules.layout.foot')
@include('backend.modules.cars.script')

resources/views/backend/modules/cms/service/index.blade.php
@include('backend.modules.layout.app')
<div class="content-wrapper">
    <section class="content-header">
        <h1>
            &nbsp;&nbsp;&nbsp;CMS Management
            <small>Preview</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li>Service</li>
            <li class="active"><a href="{{route('admin.cms.service')}}">Manage Service</a></li>
        </ol>
    </section>
    <section class="content">
        <div class="col-lg-12">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">List Of All Service </h3>
                    <a class="btn btn-primary pull-right" href="{{route('admin.cms.service.add')}}">
                        <i class="glyphicon glyphicon-plus"></i>
                        Add CMS Content
                    </a>
                </div>
                <div class="box-body">
                    <div class="table-responsive data-table-wrapper">
                        <table id="example" class="ui celled table">
                            <thead>
                            <tr>
                                <th>Id</th>
                                <th>Page name</th>
                                <th>description</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($cmsAbout as $k=> $data)
                                <tr>
                                    <td>{{$data->id}}</td>
                                    <td>{{$data->page_name}}</td>
                                    <td><?php echo  $data->description; ?></td>

                                    <td>
                                        @if($data->status )
                                            <p>Active</p>
                                        @else
                                            <p>Inactive</p>
                                        @endif
                                    </td>
                                    <td>
                                        <a style="color: green;font-size: x-large;cursor: pointer;" href="{{route('admin.cms.service.edit',$data->id)}}">
                                            <i class="fa fa-edit"></i>
                                        </a>&nbsp;&nbsp;&nbsp;&nbsp;
                                        <a style="color: red;font-size: x-large;cursor: pointer;" onclick="deleteService({{$data->id}})" data-id="{{$data->id}}">
                                            <i class="fa fa-trash"></i>
                                        </a>&nbsp;&nbsp;&nbsp;&nbsp;
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div><!-- /.box-body -->
            </div>
        </div>
    </section>
</div>
@jquery
@toastr_js
@toastr_render
@include('backend.modules.layout.foot')
@include('backend.modules.cars.script')
<script>
    $(document).ready(function() {
        var table = $('#example').DataTable( {
            lengthChange: false,
        } );
    } );
</script>
<script>
    function deleteService(input){
        var url = "{{route('admin.cms.service.delete', ":id")}}";
        url = url.replace(':id', input);
        $.ajax({
            dataType: "json",
            type: "POST",
            url: url,
            data: {
                "_token": "{{ csrf_token() }}",
            },
            success: function (data) {
                location.reload();
            }
        });
    }

</script>

resources/views/backend/modules/cms/service/script.blade.php
<script>
    function readURL(input) {
        var abc = $('#image').val();
        var fileExtension = ['jpeg', 'jpg', 'png'];
        var abc1 = abc.split('.').pop().toLowerCase();
        var reader = new FileReader();
        if($.inArray(abc1,fileExtension) !== -1)
        {
            $('#image-error').hide();
            if (input.files && input.files[0]) {
                reader.onload = function (e) {
                    $('#img')
                        .attr('src', e.target.result)
                        .width(1289)
                        .height(350);
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
        else
        {
            if (input.files && input.files[0]) {
                reader.onload = function (e) {
                    $('#img')
                        .attr('src', '#')
                        .width(0)
                        .height(0);
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
    }
</script>
<script>
    $(document).ready(function () {
        $("#carForm").validate({
            rules:{
                car_name:{
                    required:true,
                },
                seats:{
                    required:true,
                },
                ac:{
                    required:true,
                    integer:true
                },
                image:{
                    required:true,
                    extension: "png|jpeg|jpg",
                    accept: "image/jpg,image/jpeg,image/png,image/gif",
                    minImageWidth: 500,
                    maxsize: 200000,
                },
                image1:{
                    extension: "png|jpeg|jpg",
                    accept: "image/jpg,image/jpeg,image/png,image/gif",
                    maxsize: 200000,
                }
            },
            messages:{
                car_name:{
                    required:"Please Enter Car Name",
                },
                seats:{
                    required:"Please Enter Seats",
                },
                ac:{
                    required:"Please Select Proper Availability",
                    integer:"Invalid Selection"
                },
                image:{
                    required:"Please Select Proper Image",
                    extension: "Invalid File Selection",
                    accept: "Invalid File Selection",
                    maxsize: "Please Select File Less Than 2-Mb",
                },
                image1:{
                    extension: "Invalid File Selection",
                    accept: "Invalid File Selection",
                    maxsize: "Please Select File Less Than 2-Mb",
                }
            }
        });
    });
</script>
<script>
    function deleteCar(input){
        var url = "{{route('admin.cars.delete', ":id")}}";
        url = url.replace(':id', input);
        $.ajax({
            dataType: "json",
            type: "POST",
            url: url,
            data: {
                "_token": "{{ csrf_token() }}",
            },
            success: function (data) {
                location.reload();
            }
        });
    }
    function deleteAbout(input){
        var url = "{{route('admin.cms.delete', ":id")}}";
        url = url.replace(':id', input);
        $.ajax({
            dataType: "json",
            type: "POST",
            url: url,
            data: {
                "_token": "{{ csrf_token() }}",
            },
            success: function (data) {
                location.reload();
            }
        });
    }

</script>